import { Geist, Geist_Mono, Lora, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../components/common/Navbar";
import Footer from "../components/common/Footer";


export const metadata = {
  title: "Accurack Website",
  description: "Generated by Innova360",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
